@Catalog_HostAddress = https://localhost:7210/products

GET {{Catalog_HostAddress}}/
Accept: application/json

###

GET {{Catalog_HostAddress}}/1
Accept: application/json

###
POST {{Catalog_HostAddress}}/
Content-Type: application/json
{
  "id": 10,
  "name": "New Product",
  "price": 19.99,
  "description": "This is a new product.",
  "category": "Electronics",
  "imageUrl": "https://example.com/image.jpg"
}

###

PUT {{Catalog_HostAddress}}/10
Content-Type: application/json
{
  "name": "Updated Product",
  "price": 24.99,
  "description": "This is an updated product.",
  "category": "Electronics",
  "imageUrl": "https://example.com/updated-image.jpg"
}

### update price
PUT {{Catalog_HostAddress}}/1
Content-Type: application/json
{
  "name": "Updated Product",
  "price": 24.99,
  "description": "This is an updated product.",
  "category": "Electronics",
  "imageUrl": "https://example.com/updated-image.jpg"
}

###

DELETE {{Catalog_HostAddress}}/10
Accept: application/json

### Support AI

GET {{Catalog_HostAddress}}/support/give-me-a-cellphone-brand
Accept: application/json

### search
GET {{Catalog_HostAddress}}/search/Samsung 
Accept: application/json

### serachIA
GET {{Catalog_HostAddress}}/aisearch/read
Accept: application/json

####